name: Build & Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and test application
        run: mvn clean package

      - name: Upload Workflow Coverage
        run: >-
          bash <(curl -s https://bash.flowcov.io/prepare-v0.3.0) -v -d
        env:
          FLOWCOV_API_KEY: ${{ secrets.FLOWCOV_API_KEY }}
          FLOWCOV_REPOSITORY_ID: ${{ secrets.FLOWCOV_REPOSITORY_ID }}
